# Generated by Django 3.0.5 on 2020-05-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default='static/images/product.png', upload_to='static/images')),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
