# Generated by Django 3.0.5 on 2020-05-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_state', models.CharField(choices=[('OH', 'On hold'), ('IP', 'In preparation'), ('FD', 'Finalized')], default='OH', max_length=2)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
