# Generated by Django 3.0.5 on 2020-05-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('observations', models.CharField(choices=[('WS', 'Without sauce'), ('WM', 'With mustard'), ('WSD', 'With soda'), ('BWO', 'Burger without onion')], default='WS', max_length=3)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
